import type { Package } from "./PackageTypes";

/** Built-in themes shipped with Agent Terrarium */
export const BUILTIN_THEMES: Package = {
  version: 1,
  name: "Built-in Themes",
  themes: [
    {
      id: "meadow",
      name: "Meadow",
      icon: "🌿",
      sky: ["#87CEEB", "#B4E4FF", "#E8F5E9"],
      ground: "#7CB342",
      groundAccent: "#689F38",
      grass: { color: "#66BB6A", accent: "#43A047" },
      particles: { type: "leaf", color: "#A5D6A7", count: 12 },
      decorators: ["clouds", "flowers", "grass"],
      music: {
        bpm: 88,
        key: 60,
        scale: [0, 2, 4, 7, 9],
        wave: "triangle",
        bassWave: "sine",
        volume: 0.12,
        chords: [[0, 4, 7], [5, 9, 12], [7, 11, 14], [0, 4, 7]],
      },
    },
    {
      id: "night",
      name: "Night",
      icon: "🌙",
      sky: ["#0D1B2A", "#1B2838", "#1A237E"],
      ground: "#1B5E20",
      groundAccent: "#2E7D32",
      grass: { color: "#2E7D32", accent: "#1B5E20" },
      particles: { type: "star", color: "#FFECB3", count: 30 },
      decorators: ["stars", "shooting_stars", "moon", "grass"],
      music: {
        bpm: 72,
        key: 57,
        scale: [0, 2, 3, 5, 7, 8, 10],
        wave: "sine",
        bassWave: "triangle",
        volume: 0.1,
        chords: [[0, 3, 7], [5, 8, 12], [3, 7, 10], [0, 3, 7]],
      },
    },
    {
      id: "desert",
      name: "Desert",
      icon: "🏜️",
      sky: ["#FF8F00", "#FFB74D", "#FFF8E1"],
      ground: "#D4A053",
      groundAccent: "#C49040",
      particles: { type: "sand", color: "#FFE0B2", count: 8 },
      decorators: ["clouds", "cactus"],
      music: {
        bpm: 80,
        key: 62,
        scale: [0, 1, 4, 5, 7, 8, 11],
        wave: "square",
        bassWave: "triangle",
        volume: 0.1,
        chords: [[0, 4, 7], [1, 5, 8], [7, 11, 14], [0, 4, 7]],
      },
    },
    {
      id: "ocean",
      name: "Ocean",
      icon: "🌊",
      sky: ["#0277BD", "#4FC3F7", "#B3E5FC"],
      ground: "#0277BD",
      groundAccent: "#01579B",
      particles: { type: "bubble", color: "#B3E5FC", count: 15 },
      decorators: ["waves", "seaweed"],
      music: {
        bpm: 76,
        key: 55,
        scale: [0, 2, 4, 5, 7, 9, 11],
        wave: "sine",
        bassWave: "sine",
        volume: 0.1,
        chords: [[0, 4, 7], [5, 9, 12], [9, 12, 16], [7, 11, 14]],
      },
    },
    {
      id: "forest_dawn",
      name: "Forest at Dawn",
      icon: "🌅",
      sky: ["#1A0A2E", "#4A1942", "#B85C38", "#F0A500", "#FFF3CD"],
      ground: "#2E4A1E",
      groundAccent: "#1B3A0E",
      grass: { color: "#3E6B2F", accent: "#2E5A1F" },
      particles: { type: "leaf", color: "#FFECB3", count: 18 },
      decorators: ["trees", "mist", "fireflies", "grass"],
      music: {
        bpm: 68,
        key: 64,
        scale: [0, 2, 4, 7, 9],
        wave: "triangle",
        bassWave: "sine",
        volume: 0.08,
        chords: [[0, 4, 7], [7, 11, 14], [5, 9, 12], [0, 4, 7]],
      },
    },
    {
      id: "castle",
      name: "Castle",
      icon: "🏰",
      sky: ["#1A1A2E", "#16213E", "#2C3E6B"],
      ground: "#5D4E37",
      groundAccent: "#4A3C2A",
      particles: { type: "sand", color: "#FF9800", count: 6 },
      decorators: ["castle_walls", "torches", "banners"],
      music: {
        bpm: 84,
        key: 52,
        scale: [0, 2, 3, 5, 7, 8, 11],
        wave: "square",
        bassWave: "sawtooth",
        volume: 0.1,
        chords: [[0, 3, 7], [8, 11, 15], [5, 8, 12], [0, 3, 7]],
      },
    },
  ],
};

/** Built-in agent avatars shipped with Agent Terrarium */
export const BUILTIN_AGENTS: Package = {
  version: 1,
  name: "Built-in Agents",
  agents: [
    {
      id: "cat",
      name: "Cat",
      icon: "🐱",
      shape: "cat",
      colors: {
        body: "#FF9800",
        head: "#FFB74D",
        eyes: "#333",
        accent: "#E65100",
        cheek: "#FF8A80",
      },
      voice: {
        basePitch: 700,
        pitchVar: 150,
        wave: "triangle",
        syllables: 3,
        speed: 0.07,
        volume: 0.1,
      },
      personality: {
        speedMin: 30,
        speedMax: 120,
        movementStyle: "wander",
        interactionChance: 0.7,
        ballInterest: 0.9,
        chatEmojis: ["😺", "😻", "🐱", "✨", "💕"],
      },
    },
    {
      id: "copilot",
      name: "Copilot",
      icon: "🤖",
      shape: "copilot",
      colors: {
        body: "#1F6FEB",
        head: "#58A6FF",
        eyes: "#FFFFFF",
        accent: "#0D1117",
        cheek: "#90CAF9",
      },
      voice: {
        basePitch: 500,
        pitchVar: 80,
        wave: "sine",
        syllables: 4,
        speed: 0.06,
        volume: 0.08,
      },
      personality: {
        speedMin: 25,
        speedMax: 80,
        movementStyle: "patrol",
        interactionChance: 0.8,
        ballInterest: 0.5,
        chatEmojis: ["✨", "💡", "🚀", "💻", "🤝"],
      },
    },
    {
      id: "squirrel",
      name: "Squirrel",
      icon: "🐿️",
      shape: "squirrel",
      colors: {
        body: "#8D6E63",
        head: "#A1887F",
        eyes: "#333",
        accent: "#5D4037",
        cheek: "#FFAB91",
      },
      voice: {
        basePitch: 900,
        pitchVar: 200,
        wave: "triangle",
        syllables: 5,
        speed: 0.05,
        volume: 0.08,
      },
      personality: {
        speedMin: 50,
        speedMax: 180,
        movementStyle: "bounce",
        interactionChance: 0.6,
        ballInterest: 0.8,
        chatEmojis: ["🐿️", "🌰", "🍂", "😆", "💨"],
      },
    },
    {
      id: "penguin",
      name: "Penguin",
      icon: "🐧",
      shape: "penguin",
      colors: {
        body: "#37474F",
        head: "#455A64",
        eyes: "#333",
        accent: "#FF9800",
        cheek: "#F48FB1",
      },
      voice: {
        basePitch: 350,
        pitchVar: 60,
        wave: "sine",
        syllables: 2,
        speed: 0.1,
        volume: 0.1,
      },
      personality: {
        speedMin: 15,
        speedMax: 40,
        movementStyle: "wander",
        interactionChance: 0.5,
        ballInterest: 0.4,
        chatEmojis: ["🐧", "❄️", "🧊", "😊", "🐟"],
      },
    },
    {
      id: "ghost",
      name: "Ghost",
      icon: "👻",
      shape: "ghost",
      colors: {
        body: "#E8EAF6",
        head: "#F5F5F5",
        eyes: "#7E57C2",
        accent: "#B39DDB",
        cheek: "#CE93D8",
      },
      voice: {
        basePitch: 280,
        pitchVar: 40,
        wave: "sine",
        syllables: 3,
        speed: 0.12,
        volume: 0.06,
      },
      personality: {
        speedMin: 10,
        speedMax: 50,
        movementStyle: "float",
        interactionChance: 0.2,
        ballInterest: 0.1,
        chatEmojis: ["👻", "💀", "🌙", "✨", "😶"],
      },
    },
  ],
};

/** Built-in gear / accessories */
export const BUILTIN_GEAR: Package = {
  version: 1,
  name: "Built-in Gear",
  gear: [
    {
      id: "top-hat",
      name: "Top Hat",
      icon: "🎩",
      slot: "hat",
      shape: "top-hat",
      color: "#1A1A1A",
      accentColor: "#C62828",
    },
    {
      id: "party-hat",
      name: "Party Hat",
      icon: "🥳",
      slot: "hat",
      shape: "party-hat",
      color: "#E91E63",
      accentColor: "#FFC107",
    },
    {
      id: "crown",
      name: "Crown",
      icon: "👑",
      slot: "hat",
      shape: "crown",
      color: "#FFC107",
      accentColor: "#FF5722",
    },
    {
      id: "bow-tie",
      name: "Bow Tie",
      icon: "🎀",
      slot: "neck",
      shape: "bow-tie",
      color: "#E53935",
    },
    {
      id: "scarf",
      name: "Scarf",
      icon: "🧣",
      slot: "neck",
      shape: "scarf",
      color: "#1565C0",
      accentColor: "#BBDEFB",
    },
    {
      id: "sunglasses",
      name: "Sunglasses",
      icon: "🕶️",
      slot: "face",
      shape: "sunglasses",
      color: "#212121",
    },
    {
      id: "flower-crown",
      name: "Flower Crown",
      icon: "🌸",
      slot: "hat",
      shape: "flower-crown",
      color: "#F48FB1",
      accentColor: "#81C784",
    },
    {
      id: "cape",
      name: "Cape",
      icon: "🦸",
      slot: "back",
      shape: "cape",
      color: "#7B1FA2",
    },
    {
      id: "sweater",
      name: "Sweater",
      icon: "🧥",
      slot: "body",
      shape: "sweater",
      color: "#4CAF50",
      accentColor: "#FFF9C4",
    },
    {
      id: "wizard-hat",
      name: "Wizard Hat",
      icon: "🧙",
      slot: "hat",
      shape: "wizard-hat",
      color: "#311B92",
      accentColor: "#FFD54F",
    },
  ],
};
